### ISSUE TITLE
UI: Relation type shades not working

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#147]
Currently, relation shades are not set properly, leaving a mishmash of randomly coloured relations instead of consistent, type-dependent shades.

**Comment by meduzen** [comment]
I have a question regarding this issue: what was the reasoning leading to an [`old_fill`](https://github.com/DCMLab/reductive_analysis_app/blob/ee36dc85e45320e0c8867090abdd96f615b412f7/index.html#L375-L382) attribute? I’d like to know what problem it solves to determine if we can get rid of it (or use another approach).

**Comment by pettter** [comment]
The reasoning was that each relation, in addition to its type-dependent shade, also has an individual, randomized shade. This needed storing somewhere when the relations were shaded according to type.

If I had done it today, I probably would have hashed it from relation properties somehow, possibly indexed into one of the colour arrays from D3, which additionally would make it consistent across loads.

**Comment by meduzen** [comment]
I’m merging #163 as it seems fixed to me. This way I can go on. Feel free to reopen if I skipped a detail.
