### ISSUE TITLE
Fix Cmd-Z keyboard shortcut.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#151]
Some keyboard shortcuts seem broken (e.g. <kbd>Shift</kbd>–<kbd>^</kbd> for bookmarking) or in conflict with browser defaults (e.g. <kbd>Cmd</kbd>–<kbd>Z</kbd> reopens the last closed tab in Safari).

A formal test would check that all shortcuts declared in `js/conf.js` work.

Replacement shortcut: <kbd>Ctrl</kbd> + <kbd>Z</kbd>

**Comment by pettter** [comment]
Fixed in #219
