### ISSUE TITLE
XML: Move to `corresp` for linking disparate elements

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#162]
Many of the MEI XML properties that link elements are currently various more specific types, such as `copyof` or `sameas`. Most of these should instead use the less semantically well-defined `corresp`, to reduce the risk of things like MEI rendering engines being confused and trying to interpret the XML badly.

**Comment by pettter** [comment]
See https://music-encoding.org/guidelines/v4/content/analysisharm.html#analysisDescribingRelationships for more on how MEI uses and interprets `sameas` and `copyof`

**Comment by yrammos** [comment]
Strong point, thanks. Not including this as v1.0, unless you have arguments to the contrary.

**Comment by pettter** [comment]
There aren't that many places where there needs to be a change (35 lines with either keywords, but that includes comments and stuff) - the important thing is going to be backwards compatibility, i.e. finding the specific places where the app has previously been doing `sameas`/`copyof`, and changing those to `corresp`.

**Comment by pettter** [comment]
Fixed in #191
