### ISSUE TITLE
UI: Bookmark navigation

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#168]
The bookmark navigation should be placed together with the rest of the (horizontal) navigation, and given a nice UI and icons.

**Comment by meduzen** [comment]
@pettter @yrammos I have questions regarding bookmarks:
1. It seems to be possible on the master branch to bookmark a given note multiple times (see screenshot below). Is it intended?
2. When multiple notes are selected, does it make sense to bookmark them all in 1 click? Right now it only bookmark the last one that has been selected.
3. Should bookmarks be included in the exported SVG?

Screenshot: the note on the left is bookmarked once, the other has been bookmarked 3 times in a row.

![image](https://user-images.githubusercontent.com/9340937/163676965-a4c559d7-fcd1-4671-a7b2-44319718a3dd.png)

**Comment by pettter** [comment]
1. To me it doesn't make sense to bookmark a note more than once.
2. I think bookmarking just one note makes sense, and doing the last selected one makes sense to me
3. Not necessarily, but I'm not sure if it's a big deal if they are.

**Comment by yrammos** [comment]
1. I agree with Petter. I doesn't make sense to bookmark a note more than once.
2. Likewise, it doesn't make sense to bookmark a set of notes. In my opinion, the Add Bookmark button should be disabled unless exactly one note is selected.
3. Ideally not; doing so could give the false impression that bookmarks belong in the visualized encoding, whereas, strictly speaking, they do not. However, again I agree with Petter — either way it would be fine.

**Comment by meduzen** [comment]
All fine, thanks! When a bookmarked note is selected, shall the bookmark button remove the bookmark, then? 🤔

**Comment by yrammos** [comment]
Fine idea, @meduzen.

**Comment by pettter** [comment]
Looks super nice!

**Comment by yrammos** [comment]
Fantastic — and the panning is so elegant.

> Does it make sense to have a bookmark count near the bookmarks navigation icon?

It definitely does — good idea. Ideally the feature would include a temporary indicator of the bookmark number navigated _to_ (e.g. a "3/4" or "3rd out of 4"). But I'm nitpicking now.

**Comment by pettter** [comment]
Fixed with #216
