### ISSUE TITLE
UI Bug: Primary/secondary tooltip is switched

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#171]
When selecting something as primary it gets tooltipped as secondary, and vice versa. It needs to be checked that the selection matches the tooltip, which matches what actually happens in the XML graph.

**Comment by meduzen** [comment]
The behaviour I currently get is the following one:

Click: 
- tooltip: primary
- note in blue (should be red?)
- CSS class: `.note.selectednote`

![image](https://user-images.githubusercontent.com/9340937/145905133-1889d31c-c7ed-4b82-81c3-5571cf34b5f9.png)


Shift+click: 
- tooltip: secondary
- note in red (should be blue?)
- CSS class: `.note.extraselectednote`


![image](https://user-images.githubusercontent.com/9340937/145904909-35602578-a5fa-4d59-a4ef-07e3886bc996.png)

@pettter Shall we just switch the color, or is the issue at another level?

**Comment by pettter** [comment]
No it's the tooltips that are wrong - "extraselected" is the primary, while "selected" is secondary, and the colors are thus also correct.

(9)At least for now. We'll make another issue and document it properly if we change what click/shift-click means.

**Comment by meduzen** [comment]
Ooooh, I’ve always thought extraselected was the secondary. Mind blown. Thanks!
