### ISSUE TITLE
UI Bug: When several tabs are open, clicking "save" in one tries to save in all of them.

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#172]
I'm not sure if this is an issue exclusive to Firefox or something, but it happens, and it's kind of weird. I'm hoping it's Something Simple That Could Easily Be Fixed, as I can't recall it being an issue previously...

**Comment by meduzen** [comment]
I guess it’s when developing in `watch` mode (`npm run watch`), which syncs all inputs (mouse + keyboard) across all the open tabs on `localhost:3000`.

Normally it shouldn’t happen if you compile everything (npm run prod) then opens `public/index.html` in your browser using the file protocol (`file://path/to/index.html`). It it’s only in watch mode, then it’s as expected.

There used to be a way to disable this behaviour by going to `localhost:3001`, but for some reason BrowserSync settings page crash on my machine. 🤨 

Anyway, I plan to get rid of BrowserSync and move to webpack-dev-server which is way more comfortable for local development. Gonna do that after “1.0” issues are behind us.

**Comment by pettter** [comment]
Ah, that makes sense - I was running `npm run dev` but I'm assuming it has the same behaviour. Thanks for clearing it  up!
