### ISSUE TITLE
Refactor: Allow for multiple SVG/MEI pairs of successive levels of reduction

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#2]
We want to let users essentially "push" partially reduced graphs to show intermediate stages.

**Comment by pettter** [comment]
As of merging refactor_many_views_proper the first part of this undertaking is complete. The next part is to properly implement multiple actual scores, representing "layers".

**Comment by pettter** [comment]
> > Do we want to anchor notes together vertically? Perhaps with the score at different levels of zoom?
> > This is also relevant to #3 in particular
> 
> I'd say so. Ideally (i.e. most granularly) verticalization would be a reduction step in itself. That is to say, no relations would be reduced out, except for those that connect the verticalized tones.
> 
> If we get to this, it might make sense to implement it in conjunction with figured-bass layers.

I'm not sure I understand. What I was referring to above was specifically about whether views should be vertically aligned, not any transformative operation such as verticalizations.

**Comment by yrammos** [comment]
Clearly I misunderstood, then. Please disregard.

**Comment by pettter** [comment]
This is arguably fixed as of `v0.4-layers`, and new features related should go in separate issues.
