### ISSUE TITLE
Prepend AGPL header to every relevant file when building with Vite (see comments for header text)

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#206]
```
=====
This file is part of MuseReduce, a webapp for graph-based musical analysis

Copyright (C) 2022  Petter Ericson, Yannis Rammos, Mehdi Mehra, and the EPFL Digital and Cognitive Musicology Lab (DCML).

MuseReduce is free software: you can redistribute it and/or modify it under the terms of the Affero General Public License as published by the Free Software Foundation. MuseReduce is distributed without explicit or implicit warranty. See the Affero General Public License at https://www.gnu.org/licenses/agpl-3.0.en.html for more details.
=====
```

**Comment by yrammos** [comment]
Relevant files:

- non-third-party `.js`
- non-third-party `.scss` and `.css`

(both pre- and post-build)

**Comment by yrammos** [comment]
Does Vite provide a plugin for this (analogously to those available for WebPack)?

**Comment by meduzen** [comment]
Should HTML files also receive the license header, like in #199?

> Does Vite provide a plugin for this (analogously to those available for WebPack)?

As Vite is based on Rollup, maybe [this plugin](https://www.npmjs.com/package/rollup-plugin-license) could fill the need. From what I read [in this issue](https://github.com/mjeanroy/rollup-plugin-license/pull/988), it should work with Vite. [Vite docs](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility) states that most Rollup plugins are usable in Vite out of the box.

Is there a reason why it would be needed through Vite on top of a GitHub action?

(Side note: [I changed my name](https://github.com/DCMLab/reductive_analysis_app/commit/4fc292b645c32b29dd7df43c6491e1eb8dd07cab) on the main branch, it was misspelled.)

**Comment by yrammos** [comment]
@meduzen thanks for these suggestions. The GitHub action was a potential kludge that I explored, then soon enough abandoned, in case Vite didn't provide the necessary facilities. I have since reverted these commits.
