### ISSUE TITLE
First batch of unit tests

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#40]
There should be a continuous integration system that also runs unit tests and on the whole makes sure that no bugs are introduced. By judicious use of "toggle_selected" and such things, it should not be impossible to write these, though I am not entirely sure how to write them properly, with all the global state that's involved.

- [x] Integrate framework into webapp.
- [x] Discuss Petter's manual tests and produce an (ideally exhaustive) test suite.
- [x] Write the tests.

**Comment by yrammos** [comment]
@petter pushed a working infrastructure to the `tests` branch.
