### ISSUE TITLE
Use css classes instead of css attributes in JS files.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#57]
That is, avoid such expressions as `item.style.fillOpacity` and prefer (something like) `item.classList.add("filledItem")` (plain JS) or `item.addClass("filledItem")` (jQuery).

This would facilitate UI improvements such as #56.

**Comment by pettter** [comment]
This would also require switching quite a few `.getAttribute("class") == "foo"`  comparisons to something like `.classlist.contains("foo")" but it definitely looks like a good change of practise to me.

**Comment by pettter** [comment]
A refactor has been pulled in #58. Styles are still not fixed, but at least various other things no longer depend on there being only one class.

**Comment by pettter** [comment]
Much further work has been done on the refactor_style_to_css branch, which I think should cover it. The old commented-out code should be removed, and then I think a pull request and merge might be in order.

**Comment by pettter** [comment]
Also the tests currently fail on that branch, but that may be simply because style information has moved rather than it being Wrong.

**Comment by pettter** [comment]
This has been fixed in 7e1daab, more or less, and merged into master as of `0.4-layers`
