### ISSUE TITLE
Cannot delete metarelation.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#62]
Unless I'm embarrassingly mistaken, there is currently no UI for deleting a meta-relation.

**Comment by yrammos** [comment]
> This is accurate. Deletion of relations interacts badly with meta-relation in general.

I noticed this, too. (It probably warrants a separate issue.) But what about deleting *meta*-relations only?

**Comment by pettter** [comment]
With the same caveats about cascading effects, it shouldn't be too much work to modify `delete_relation` to work also on metarelations.
