### ISSUE TITLE
Create simple webform for adding authorship annotations.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#65]
Based on prior Mattermost discussion, the app would benefit from a simple HTML form for authorship annotations (including the analysis author and the encoder—especially if the latter departs from the notation of the former, e.g. by filling-in underdetermined spans or making interpretive inferences).

MEI/TEI standards may also have to be adhered to.

Editing the MEI file directly is always a possibility, but could result in inconsistent uses of relevant tags/attributes and would also incur the risk of corrupt XML.

**Comment by pettter** [comment]
Looking through the MEI guidelines, it looks to me that we should add/modify an entry to the `respStmt` in the `meiHead` `titleStmt`. One for the analyst, and one for the analysis encoder (which may be the same person). This lets us add responsibility metadata for each node in the graph using the `@resp` attribute of the `label`.

We could also add a `source` element describing the full bibliographic information about the source of the analysis, and use that with `@source` attributes as well.

**Comment by pettter** [comment]
For the future, if/when things are stored and continuously updated, it may also be of interest to start using the `revision` tags, possibly with some automatic processing involved.

**Comment by yrammos** [comment]
> For the future, if/when things are stored and continuously updated, it may also be of interest to start using the `revision` tags, possibly with some automatic processing involved.

@pettter might you be referring to the `<revisionDesc>` tag?

> Looking through the MEI guidelines, it looks to me that we should add/modify an entry to the `respStmt` in the `meiHead` `titleStmt`. One for the analyst, and one for the analysis encoder (which may be the same person).

A sound idea, I think. Perhaps we could then apply `@type` attributes to `respStmt` to differentiate between `encoder` and `analyst` roles.

**Comment by pettter** [comment]
> @pettter might you be referring to the <revisionDesc> tag?

Myep, should've checked back to make sure I got the tag name right.

> A sound idea, I think. Perhaps we could then apply @type attributes to respStmt to differentiate between encoder and analyst roles.

Yes exactly. They detail a bunch of different ways to denote roles in the documentation, and we'll have to take a look at what is the most appropriate for our case.

**Comment by pettter** [comment]
The Basic version is up as of merging #86
